apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Demo Applications
  name: demo-apps
spec:
  domain: tap
  owner: platform-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=pacman
    prometheus.io/rule: sum(rate(container_cpu_usage_seconds_total{pod=~"^pacman-.*-deployment.*"}[1m])) by (pod)
    grafana/dashboard-selector: pacman
  description: Sample Javascript Based Pacman Using Kaniko
  name: pacman
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: demo-apps
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=demo-app
    prometheus.io/rule: container_cpu_usage_seconds_total{pod=~"^demo-app-.*-deployment.*"}
  description: Tanzu Java Web App Demo
  name: demo-app
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: demo-apps
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=petclinic
    prometheus.io/rule: sum(rate(container_network_receive_packets_total{pod=~"^petclinic-.*-deployment.*"}[1m])) by (pod),sum(rate(container_network_transmit_packets_total{pod=~"^petclinic-.*-deployment.*"}[1m])) by (pod)
    grafana/dashboard-selector: "url == 'http://grafana.tap-17.terasky.demo/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=tdp&var-type=deployment&var-workload=petclinic-00001-deployment'"
  description: Spring Petclinic
  name: petclinic
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: demo-apps
  type: service
