apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Demo Applications
  name: demo-apps
spec:
  domain: tap
  owner: platform-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    sonarqube.org/project-key: vrabbi_js-pacman
    backstage.io/kubernetes-id: pacman
    backstage.io/source-location: url:https://github.com/vrabbi/js-pacman/blob/master/
    prometheus.io/rule: sum(rate(container_cpu_usage_seconds_total{pod=~"^pacman-.*-deployment.*"}[1m])) by (pod)
    grafana/dashboard-selector: pacman
    goharbor.io/repository-slug: tap/workloads/pacman-tdp
    github.com/project-slug: vrabbi/js-pacman
    janus-idp.io/tekton: pacman
  description: Sample Javascript Based Pacman Using Kaniko
  name: pacman
  title: Pacman
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: demo-apps
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    sonarqube.org/project-key: vrabbi_java-web-app
    backstage.io/kubernetes-id: demo-app
    prometheus.io/rule: container_cpu_usage_seconds_total{pod=~"^demo-app-.*-deployment.*"}
    goharbor.io/repository-slug: tap/workloads/demo-app-tdp
    grafana/dashboard-selector: demo-app
    github.com/project-slug: vrabbi/java-web-app
  description: Tanzu Java Web App Demo
  title: Demo Java App
  name: demo-app
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: demo-apps
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  links:
    - url: https://petclinic.tdp.tap-17.terasky.demo
      title: Application
      icon: dashboard
  annotations:
    sonarqube.org/project-key: vrabbi_spring-petclinic
    vault.io/secrets-path: tdp/demo/secrets/app-01
    dev.azure.com/project-repo: petclinic/petclinic
    backstage.io/kubernetes-id: petclinic
    prometheus.io/rule: sum(rate(container_network_receive_packets_total{pod=~"^petclinic-.*-deployment.*"}[1m])) by (pod),sum(rate(container_network_transmit_packets_total{pod=~"^petclinic-.*-deployment.*"}[1m])) by (pod)
    goharbor.io/repository-slug: tap/workloads/petclinic-tdp
    grafana/dashboard-selector: petclinic
    github.com/project-slug: vrabbi/spring-petclinic
    backstage.io/techdocs-ref: url:https://github.com/vrabbi/spring-petclinic/tree/main
  description: Spring Petclinic
  title: Spring Petclinic
  name: petclinic
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: platform-team
  system: demo-apps
  type: service
  providesApis:
  - tdp/petclinic-db424db5
  
