metadata:
  namespace: default
  name: tanzu-java-web-app-v2
  title: Tanzu Java Web App-v2
  description: A sample Spring Boot web application built with Tanzu supply-chain
  tags:
    - java
    - spring
    - gradle
    - maven
    - web
    - tanzu
    - devcontainer
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
spec:
  type: service
  parameters:
    - definitions: {}
      title: Configure accelerator
      properties:
        projectName:
          title: Name
          description: Provide a name for your new project
          type: string
          default: tanzu-java-web-app
        buildTool:
          title: Build Tool
          type: string
          enum:
            - maven
            - gradle
          enumNames:
            - Maven (https://maven.apache.org/)
            - Gradle (https://gradle.org/)
          default: maven
          ui:widget: select
        springBootVersion:
          title: Spring Boot version
          type: string
          enum:
            - "2.7"
            - "3.0"
            - "3.1"
          enumNames:
            - Spring Boot 2.7
            - Spring Boot 3.0 (Requires Java 17)
            - Spring Boot 3.1 (Requires Java 17)
          default: "2.7"
          ui:widget: select
        nativeBuild:
          title: Support native GraalVM builds (Requires Spring Boot 3.0 or 3.1 and Java
            17)
          type: boolean
          default: false
          ui:widget: checkbox
        javaVersion:
          title: Java version to use
          type: string
          enum:
            - "1.8"
            - "11"
            - "17"
          enumNames:
            - Java 8
            - Java 11
            - Java 17
          default: "11"
          ui:widget: select
        includeBuildToolWrapper:
          title: Include Build Tool wrapper support
          type: boolean
          default: true
          ui:widget: checkbox
        includeDevContainer:
          title: Include .devcontainer.json (amd64 support only)
          description: Experimental support for "Visual Studio Code Dev Containers".
          type: boolean
          default: false
          ui:widget: checkbox
      required:
        - projectName
        - buildTool
      dependencies:
        buildTool:
          oneOf:
            - properties:
                buildTool:
                  const: gradle
                ide:
                  title: IDE
                  type: string
                  enum:
                    - intellij
                    - vscode
                  enumNames:
                    - IntelliJ Idea
                    - Visual Studio Code
                  default: intellij
                  ui:widget: select
              required: []
            - properties:
                buildTool:
                  not:
                    anyOf:
                      - const: gradle
      ui:order:
        - projectName
        - buildTool
        - ide
        - springBootVersion
        - nativeBuild
        - javaVersion
        - includeBuildToolWrapper
        - includeDevContainer
    - title: Git repository
      properties:
        _createGitRepo:
          title: Create a new repository to store the newly generated project?
          type: boolean
          defaultValue: false
      dependencies:
        _createGitRepo:
          oneOf:
            - properties:
                _createGitRepo:
                  enum:
                    - false
            - properties:
                _createGitRepo:
                  enum:
                    - true
                bsGitRepository:
                  title: Repository Location
                  type: string
                  ui:field: RepoUrlPicker
                  ui:options:
                    requestUserCredentials:
                      secretsKey: USER_OAUTH_TOKEN
                      additionalScopes:
                        github:
                          - workflow
                    allowedHosts:
                      - github.com
                bsGitBranch:
                  title: Default Branch
                  type: string
                  default: main
                repoVisibility:
                  tile: Repo Visibility
                  type: string
                  enum:
                    - private
                    - internal
                    - public
                  enumNames:
                    - Private
                    - Internal
                    - Public
                  default: private
                  ui:widget: select
    - title: Backstage Config
      properties:
        _registerComponent:
          title: Should this entity be auto registered in the portal
          type: boolean
          defaultValue: false
      dependencies:
        _registerComponent:
          oneOf:
            - properties:
                _registerComponent:
                  enum:
                    - false
            - properties:
                _registerComponent:
                  enum:
                    - true
                owner:
                  title: Owner
                  type: string
                  description: Owner of the component
                  ui:field: OwnerPicker
                  ui:options:
                    allowedKinds: [Group]
                system:
                  title: System
                  type: string
                  description: System the component belongs to
                  ui:field: EntityPicker
                  ui:options:
                    allowedKinds: [System]
                    defaultKind: System
                lifecycle:
                  title: Lifecycle
                  type: string
                  enum:
                    - experimental
                    - production
                    - deprecated
                  enumNames:
                    - Experimental
                    - Production
                    - Deprecated
                  default: experimental
                  ui:widget: select
  steps:
    - id: fetch-accelerator
      name: Fetch accelerator and fragments
      action: vmware:accelerator-fetch-flux
      input:
        accelerator:
          tanzu-java-web-app:
            tarball: http://source-controller-manager-artifact-service.source-system.svc.cluster.local./imagerepository/accelerator-system/tanzu-java-web-app-acc-dvk9v/41a58db3312ee14bd9edeebb892a2eb5b2309af49f05bfa5112c9f38e2690184.tar.gz
        fragments:
          build-wrapper-gradle:
            tarball: http://source-controller-manager-artifact-service.source-system.svc.cluster.local./imagerepository/accelerator-system/build-wrapper-gradle-frag-mlfxp/16e94db5d608d793e25c75eb761707d732e1fff7105be83949ff4ba11bf864fb.tar.gz
          build-wrapper-maven:
            tarball: http://source-controller-manager-artifact-service.source-system.svc.cluster.local./imagerepository/accelerator-system/build-wrapper-maven-frag-r86pp/386af55b597bbb87a1a6aa0f04c46392e72d9c9e12ab60332401a859f765b250.tar.gz
          devcontainer:
            tarball: http://source-controller-manager-artifact-service.source-system.svc.cluster.local./imagerepository/accelerator-system/devcontainer-frag-dcc65/0c9f2b8294149c6b3d8b2138eb074d010bdffb234ea65d7f73f65c16d710e618.tar.gz
          java-version:
            tarball: http://source-controller-manager-artifact-service.source-system.svc.cluster.local./imagerepository/accelerator-system/java-version-frag-wm794/a75abbf6fc247d96aebb2526e6bcc5e5452cbb4e2f6094ea2c75fc54a6e128c3.tar.gz
          tap-workload:
            tarball: http://source-controller-manager-artifact-service.source-system.svc.cluster.local./imagerepository/accelerator-system/tap-workload-frag-w8dd7/f17ac7f6efca5cdeaf27c98420afda15fd424e67821e215ca736911f266f731f.tar.gz
    - id: invoke-accelerator
      name: Invoke accelerator engine
      action: vmware:accelerator-invoke
      input:
        options: ${{ parameters }}
        versions: ${{steps['fetch-accelerator'].output.versions}}
    - id: populate-amr
      name: Record Accelerator Invocation in AMR
      action: vmware:populate-amr
      if: ${{ not parameters['_explore'] }}
      input:
        provenance: ${{steps["invoke-accelerator"].output.provenance}}
    - id: create-component-yaml
      action: catalog:write
      if: ${{ parameters['_registerComponent']
      name: Create Catalog Info YAML
      input:
        filePath: result/auto-generated-catalog-info.yaml
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: test
            annotations:
              backstage.io/kubernetes-label-selector: "app.kubernetes.io/part-of=${{ parameters.projectName }}"
              backstage.io/techdocs-ref: dir:.
              github.com/project-slug: ${{ parameters.bsGitRepository | projectSlug }}
              grafana/dashboard-selector: ${{ parameters.projectName }}
              janus-idp.io/tekton: ${{ parameters.projectName }}
          spec:
            type: service
            system: ${{ parameters.system | parseEntityRef | pick('name') }}
            lifecycle: ${{ parameters.lifecycle }}
            owner: ${{ parameters.owner }}
    - id: create-repo-github
      name: Create github repo
      if: ${{ not parameters['_explore'] and parameters['_createGitRepo'] and
        (parameters.bsGitRepository.startsWith('github.com')) }}
      action: publish:github
      input:
        repoUrl: ${{ parameters.bsGitRepository }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        defaultBranch: ${{ parameters.bsGitBranch }}
        sourcePath: result
        repoVisibility: ${{ parameters.repoVisibility }}
    - id: publish-zip
      name: zip files from accelerator and make them available to download
      action: vmware:publish-zip
      input:
        root-dir: ${{ parameters.projectName }}/
        source-dir: result
    - id: register
      if: ${{ not parameters['_explore'] and parameters['_registerComponent'] and parameters['_createGitRepo'] }}
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['create-repo-github'].output.repoContentsUrl }}
        catalogInfoPath: '/auto-generated-catalog-info.yaml'
        optional: true
  output:
    links:
      - title: Repository
        url: ${{ steps['create-repo-github'].output.remoteUrl }}
      - title: Get zip file
        url: data:application/zip;base64,${{ steps["publish-zip"].output.file }}
        download: ${{ parameters.projectName }}.zip
        acceleratorName: tanzu-java-web-app
        createdGitRepo: ${{ parameters["_createGitRepo"] }}
        uuid: ${{steps["invoke-accelerator"].output.provenance.id}}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
