apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: tanzu
  description: Everything related to the Tanzu Application Platform
  links:
    - url: https://www.vrabbi.cloud/post/category/tap/
      title: vRabbi TAP Blogs
      icon: docs
    - url: https://vrabbi.cloud/post/category/tkg/
      title: vRabbi TKG Blogs
      icon: docs
    - url: https://vrabbi.cloud/post/category/carvel/
      title: vRabbi Carvel Blogs
      icon: docs
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
      title: Official TAP Documentation
      icon: docs
    - url: https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/index.html
      title: Official TKG Documentation
      icon: docs
    - url: https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/index.html
      title: Official TMC Documentation
      icon: docs
    - url: https://carvel.dev
      title: Official Carvel Documentation
      icon: docs
spec:
  owner: cna-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Demo Applications
  name: carvel
spec:
  domain: tanzu
  owner: tkg-admins
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-label-selector: app=kapp-controller
    github.com/project-slug: 'carvel-dev/kapp-controller'
    prometheus.io/rule: carvel_packageinstall_info{status="True"},carvel_packageinstall_info{status="False"}
    'backstage.io/techdocs-ref': dir:.
    #grafana/dashboard-selector: "url == 'http://grafana.tap-17.terasky.demo/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=tdp&var-type=deployment&var-workload=petclinic-00001-deployment'"
  description: Kapp Controller
  name: kapp-controller
  tags:
  - v1alpha1
spec:
  lifecycle: production
  owner: tkg-admins
  system: carvel
  type: service
